### ISSUE TITLE
We need to test whether Alexa can even transcribe the stories that users tell it.

### ISSUE THREAD

**Issue by danielmartincraig** [AlldredgeCraigSeniorProjectTeam/oral-history#1]

**Comment by danielmartincraig** [comment]
I'm going to design a test of Alexa's facility in regards to transcription.

**Comment by daniel-craig** [comment]
https://github.com/AlldredgeCraigSeniorProjectTeam/oral-history/commit/40ea3dae08a0c36ee1e26ae95b028c5038361e2f

This issue has been satisfied - Alexa transcribes the stories without issue.
